### PR TITLE
[IN-23][Preprints] Fall back to use fullName when user have no givenName and familyName

### PR DESCRIPTION
**Pull request by adlius**
## Purpose

This is the second of two PRs (the first one is [here](https://github.com/CenterForOpenScience/ember-osf/pull/346)) to make sure preprint detail page will fall back to using fullName of contributors.

## Summary of Changes

In `index.hbs`, use newly added `name` field of the `user` model.

## Side Effects / Testing Notes

There are four scenarios to test:
1. givenName, familyName and fullName are all defined: should show "{givenName} {familyName}"
2. only givenName and fullName are defined: should show "{fullName}"
3. only familyName and fullName are defined: should show "{fullName}"
4. only fullName is defined: should show "{fullName}"

Note: fullName is always defined because it is a required field for users.

## Ticket

https://openscience.atlassian.net/browse/IN-23

# Reviewer Checklist

- [ ] meets requirements
- [ ] easy to understand
- [ ] DRY
- [ ] testable and includes test(s)
- [ ] changes described in `CHANGELOG.md`

### CODE REVIEW

**Comment by adlius** [comment]
@alexschiller I would always wait for emberosf changes to be merged before dealing with CHANGELOG/package.json/yarn.lock conflicts, as it could take weeks before the next emberosf release and the CHANGELOG could still keep growing.

**Comment by laurenbarker** [comment]
@alexschiller @adlius this PR can be based on `release/next-interfaces` and merged in when ready.

**Comment by alexschiller** [comment]
@adlius  Changelog conflicts.

**Comment by adlius** [comment]
@alexschiller Resolved.

**Pull request merged**
