### PR TITLE
[IN-72][Preprints] Prettify display of preprint providers logo on preprints landing page

### PR DESCRIPTION
**Pull request by hmoco**
## Ticket
https://openscience.atlassian.net/browse/IN-72

## Purpose
Remove the carrousel and instead display, in a non-terrible manner, all the providers we have.

## Changes
New component `pretty-column-display` that takes in the number of columns and an array of items, and a template, and display rows of those items in the template in a pleasant manner.

### After:
screen shot 2017-10-18 at 3 23 05 pm

### Before:
screen shot 2017-10-18 at 4 02 37 pm

### CODE REVIEW

**Comment by jamescdavis** [comment]
This a nice solution, but probably nicer to try using a pure CSS solution similar to: https://codepen.io/jamescdavis/pen/ppjEOK

**Comment by hmoco** [comment]
Not sure which branch to point to atm, so will just point to develop for a cleaner diff for now, can branch off a release branch and cherry-pick the relevant commits if needed.

**Comment by hmoco** [comment]
Oops that didn't help one bit.... @jamescdavis, at this point I think I just need a new branch, where should I point it to?

**Comment by laurenbarker** [comment]
@hmoco should this PR be closed in favor of #518 ?

**Comment by alexschiller** [comment]
Closing in favor of #518 -- this looks like a dupe of that PR but without the changelog. If that's wrong, please re-open.

**Pull request closed without merging**
