### PR TITLE
[hold] Keen IO view/ download counts on project detail page [PREP-166]

### PR DESCRIPTION
**Pull request by abought**
⚠️ This PR depends on an OSF PR: https://github.com/CenterForOpenScience/osf.io/pull/6219/files
❗ There are special instructions to test this locally
## Purpose

Display keen.io download metrics on the content page. 

Precursor to styling work planned by @caneruguz 

For a file with no known metrics (or before keen request has returned):
screen shot 2016-08-26 at 6 46 31 pm

For a file with metrics available:
screen shot 2016-08-26 at 6 47 20 pm
## Notes for reviewers
- Links to relevant debugging information are [in the preprints team private flow](https://www.flowdock.com/app/cos/intern-project-preprints/threads/XYIru_-101_vdqZVJOEbD1U1sPU). 
- Your local files may not send analytics data to keen, so the remote server will not respond with information about your file. You can test this PR by fudging several lines of code to give keen a fake access key and file ID (see flowdock for values). The metrics displayed on the resulting page will be for a file that exists in production.
- If you do not configure a keen project ID, no keen requests will be sent.
## Deployment notes
- In config/environment.js, you must set the appropriate `ANALYTICS.keenProjectId` for your environment. (it is shared across all projects) The default value, provided by Fitz, is considered public information and corresponds to OSF production environment.
## Ticket

https://openscience.atlassian.net/browse/PREP-166
related to https://openscience.atlassian.net/browse/PREP-133

### CODE REVIEW

**Comment by abought** [comment]
Test failures are unrelated and appear due to CDN configuration not recognizing the test environment.

**Comment by abought** [comment]
Brought up to date with most recent changes to 6219, in case it turns out to be useful.

**Comment by icereval** [comment]
NOTE: Future incarnations of this PR will need to send View count updates to Keen not just display.

**Comment by abought** [comment]
Is this PR still relevant? I know that others were working to iterate on it; can it be closed?

**Comment by pattisdr** [comment]
Hmm. I was working on better tracking Keen download counts as a part of this ticket: https://openscience.atlassian.net/browse/EOSF-347, where I'm adding keen tracking for a few other items. I've been working on write-only stuff. Sending more data to keen, not displaying.

**Comment by laurenbarker** [comment]
Closing since this PR is stale.

**Pull request closed without merging**
